### ISSUE TITLE
"LockDown should not be used to log in to your learning system"

### ISSUE THREAD

**Issue by Gregory67160** [gucci-on-fleek/lockdown-browser#17]
Lockdown requires me to use Edge to log into Brightspace and click the link to launch lockdown. Is there any way to get this to work without getting the "remote desktop/terminal services" error when launching lockdown a second time (and from the link)?
![Screenshot 2023-06-06 150858](https://github.com/gucci-on-fleek/lockdown-browser/assets/93414707/322e0c89-eec8-4f8d-9473-6accc05df15b)
(My exam isn't available yet so I'm unable to test it out)
Version: 2.1.0.07

**Comment by gucci-on-fleek** [comment]
This _should_ work (see #5 and f73c3f28), but there's always a chance that it won't.

I'll close this for now, but please add new comments and/or reopen the issue if something doesn't work.
