### ISSUE TITLE
Can't open sandbox.wsb

### ISSUE THREAD

**Issue by huzzxin** [gucci-on-fleek/lockdown-browser#21]
![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/95949655/70cf5bb4-8024-418b-867b-aaa8ada08f87)

**Comment by gucci-on-fleek** [comment]
You need to use the one in `runtime_directory/`, **not** the one in `src/`.

> ## Running
> 1. Build the project as shown above.
> 2. Download the _Respondus Lockdown Browser_ and place it in `runtime_directory\`.
> 3. **Double-click `Sandbox.wsb` (it’s in `runtime_directory\`)**
> 4. Wait. It’ll take about a minute, but eventually the _Lockdown Browser_ will open, completely automatically.
>
> https://github.com/gucci-on-fleek/lockdown-browser#running

**Comment by huzzxin** [comment]
There isn't one in runtime_directory, is it supposed to make one after running sandbox_run.ps1? When I click that powershell file it opens powershell for a second and just closes

**Comment by gucci-on-fleek** [comment]
> is it supposed to make one after running sandbox_run.ps1? When I click that powershell file it opens powershell for a second and just closes

Well `sandbox_run.ps1` starts with

https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/runtime_directory/sandbox_run.ps1#L6

so doing that probably wasn't a great idea. Running 
```powershell
sfc /scannow
dism /online /cleanup-image /restorehealth
sfc /scannow
```
as an Administrator should hopefully undo the damage. (Realistically, this probably isn't necessary. The script won't be able to do anything at all unless you run it as admin, and if you just double-clicked it, it would have ran as a regular user).

---

Anyways,

> There isn't one in runtime_directory

That suggests that either the build process failed somehow, or you never ran the build steps to begin with.

Building is pretty easy, provided that you have all the prerequisites installed:

> ## System Requirements
>   - Windows 10 **Pro** or **Enterprise**
>   - [Visual Studio C++ Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools)
>   - [git](https://git-scm.com/download/win)
> 
> ## Building
> Clone the repository, then run `build.ps1`. Then, [install the _Windows Sandbox_](https://www.howtogeek.com/399290/how-to-use-windows-10s-new-sandbox-to-safely-test-apps/). That's it!
>
> https://github.com/gucci-on-fleek/lockdown-browser#system-requirements

If you've already done all that, then did the build script give you any error messages?

**Comment by huzzxin** [comment]
![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/95949655/33712230-3f08-4e85-93d7-cf27d68b653f)
I found the issue

**Comment by gucci-on-fleek** [comment]
Running 

```powershell
Set-ExecutionPolicy unrestricted
```

will solve this specific issue, but if you can't solve that on your own then this project may not be for you.

**Comment by huzzxin** [comment]
![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/95949655/e11f5f0f-9c58-4410-81d4-7ce9b0a998ca)
Not sure why it says this, i have the visual tools installed

**Comment by huzzxin** [comment]
> ![image](https://user-images.githubusercontent.com/95949655/250525338-e11f5f0f-9c58-4410-81d4-7ce9b0a998ca.png) Not sure why it says this, i have the visual tools installed

Reinstalling visual studio and added entire desktop development with C++ i think i didnt add last time.
Everything works perfectly now, thanks alot.

**Comment by huzzxin** [comment]
Close
