### ISSUE TITLE
Video/Mic Input Not Working

### ISSUE THREAD

**Issue by Rynost** [gucci-on-fleek/lockdown-browser#27]
Hello,

I have attempted the following:

-Used Sandbox-with-Microphone-Camera.wsb instead.
-Manually added AllowVideoInput into my Registry Editor.

The sandbox seems to be detecting the device in Device Manager, but it is completely unusable.

Is there a solution to this issue?

Thanks.

**Comment by gucci-on-fleek** [comment]
Is the standard Windows "Camera" app available in the _Sandbox_? If so, what happens when you open it? Does it detect the webcam? 

If the app isn't preinstalled in the _Sandbox_ for some reason, try testing the camera with this link

> [`https://mozilla.github.io/webrtc-landing/gum_test.html`](https://mozilla.github.io/webrtc-landing/gum_test.html
)

with Edge (inside the _Sandbox_). Does that work?

**Comment by Rynost** [comment]
![gitsnap](https://github.com/gucci-on-fleek/lockdown-browser/assets/23021922/30c7d573-a16c-47fe-a874-94a1cbf7000b)
![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/23021922/f32330d2-b329-4591-b46d-c017e328eefc)

I do not have the "Camera" app, nor did the Edge webcam test work.

Thanks for the quick response!

**Comment by gucci-on-fleek** [comment]
Hmm, okay. Can you try the "Camera" app on the host system (outside of the _Sandbox_) if it exists. And can you also try that same link on the host system too? Do they work there?

**Comment by Rynost** [comment]
Outside the sandbox, I have the "Camera" app, and the link shows my camera.

**Comment by gucci-on-fleek** [comment]
Can you upload or paste the contents of your `Sandbox-with-Microphone-Camera.wsb` here? Perhaps the file got corrupted somehow? 

And also, what's your current version+build of Windows?

**Comment by Rynost** [comment]
Version	10.0.18363 Build 18363

I changed the .wsb to .txt so I can upload it here:
[Sandbox-with-Microphone-Camera.txt](https://github.com/gucci-on-fleek/lockdown-browser/files/12472284/Sandbox-with-Microphone-Camera.txt)

**Comment by gucci-on-fleek** [comment]
According to [this post](https://www.reddit.com/r/Windows10/comments/hgcizd/build_2004s_sandbox_can_access_webcam_now/), enabling the Webcam in the _Sandbox_ requires Windows 10 build 2004, but you're running build 1909 which is too old. 

So the only solution here would be to update Windows (which you should probably do regardless since [1909 has been out of support for over a year now](https://en.wikipedia.org/wiki/Windows_10,_version_1909)).
