### ISSUE TITLE
Error after trying to launch

### ISSUE THREAD

**Issue by wabwest10** [gucci-on-fleek/lockdown-browser#28]
it wouldn't let me access the blackboard after I launched the sandbox, it only says that I had to connect to the University Wi-Fi, but I was already connected to the University Wi-Fi. this problem didn't happen when i launched the sandbox at home.

**Comment by gucci-on-fleek** [comment]
Maybe try bridging the network? I haven't tested it, but [these instructions seem correct to me](https://www.guidingtech.com/fix-windows-sandbox-no-internet-connection-issue/) (only the bridging stuff, ignore the rest).

**Comment by wabwest10** [comment]
the day after I had the problem I went back to the university to try the bridge with the university wifi, but I don't know why as soon as I launched the sandbox I was able to access blackboard again as before. Why do you think it gave me that problem the day before? perhaps because it was the first time I launched the sandbox by connecting to the University wifi?

**Comment by wabwest10** [comment]
or because the day I had the problem he had a university test to do and it was some university software that blocked the possibility of accessing bboard and respondus with the sandbox?

**Comment by gucci-on-fleek** [comment]
Yeah, that's weird. I'm not too sure what happened, but it seems to work now so I'm going to close this issue. Feel free to reopen it though if the problem happens again.
