### ISSUE TITLE
Error to start lockdown browser : Remote Desktop or Terminal Service are active

### ISSUE THREAD

**Issue by antonionappo** [gucci-on-fleek/lockdown-browser#29]
This browser can't be used while Remote Desktop or Terminal Service are active.

**Comment by gucci-on-fleek** [comment]
[From the main instructions:](https://github.com/gucci-on-fleek/lockdown-browser#you-get-a-terminal-services-error-message)

> ### You get a “Terminal Services” error message
> 
> If the _Lockdown Browser_ fails to launch, **do not double-click** the file on the VM's desktop. Instead, open a PowerShell prompt inside the VM and run:
> 
> ```powershell
> cd C:\Users\WDAGUtilityAccount\Desktop\runtime_directory\
> .\withdll.exe /d:GetSystemMetrics-Hook.dll "C:\Program Files (x86)\Respondus\LockDown Browser\LockDownBrowser.exe"
> ```
> 
> Of course, this is usually symptomatic of another issue, so please make sure that you have followed all the earlier instructions.

You've given **zero** additional information, so there's not much I can do to help here. I'll close this for now, but please, feel free to add a comment with more information and reopen the issue if this still doesn't work.

**Comment by antonionappo** [comment]
i have responded you under issue number 15.
