### ISSUE TITLE
3-Finger Swipe Gesture Detected

### ISSUE THREAD

**Issue by ryangodburn** [gucci-on-fleek/lockdown-browser#32]
I'm not sure if there is any way to bypass this being detected but it wouldn't hurt to bring it up here.
![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/44278185/6678e696-9443-4d2c-bb69-3aa4ed8f1fc7)

**Comment by gucci-on-fleek** [comment]
Any input directed to the _Sandbox_ is passed through to the _Browser_; that's how you're still able to type and use your mouse with the _Browser_. My only guess on how to fix this would be #12, but that's already been merged, so I'm out of ideas. 

Feel free to comment or submit a PR if you can think of some way to fix this though.
