### ISSUE TITLE
Any way to run sandbox without respondus opening instantly?

### ISSUE THREAD

**Issue by DzXAnt22** [gucci-on-fleek/lockdown-browser#35]
Hello. Just doing some research on this program but am unable to log into my school or access any quizzes from lockdown browser itself, I need to access them through a special link on the regular browser, and then that link opens respondus. Is there any way to run this bypass without respondus opening instantly?

**Comment by ericswpark** [comment]
You can close out of the browser once it is initially installed, and then use any browser that you'd like.

**Comment by DeadFrostt** [comment]
Hey Eric have you tried this with the latest lockdown browser version? does it still work with quizzes?

**Comment by ericswpark** [comment]
Yes it does work but I cannot guarantee that it will for all the different installers that LDB has.

**Comment by gucci-on-fleek** [comment]
@ericswpark

> You can close out of the browser once it is initially installed, and then use any browser that you'd like.

Yep, this is the correct way to launch the _Lockdown Browser_ via an external link. Just make sure that the alternate browser (probably Edge) is _inside_ the _Sandbox_, not outside.

@DzXAnt22
> Is there any way to run this bypass without respondus opening instantly?

I'd recommend just using @ericswpark's method, but you could comment-out the last line of `sandbox_run.ps1` if you really want.

https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/runtime_directory/sandbox_run.ps1#L41

@DeadFrostt
> Hey Eric have you tried this with the latest lockdown browser version? does it still work with quizzes?

This method _should_ always work, but if not, you can [manually paste the link into the command-line and run it that way](https://github.com/gucci-on-fleek/lockdown-browser/issues/43#issuecomment-1902692418). Hopefully shouldn't be necessary though.
