### ISSUE TITLE
LockDown Browser - Version 2.1.1.04 detects "VmComputeAgent.exe" 

### ISSUE THREAD

**Issue by bluesangheili** [gucci-on-fleek/lockdown-browser#37]
The usual pop-up appears saying "You must close the following application...":
VmComputeAgent.exe
(VmComputeAgent.exe)
Do you want LockDown Browser to attempt to close this application for you?

After this, Windows Sandbox closes itself. Perhaps Respondus patched this?

I have followed thoroughly the whole tutorial for several hours and managed to get the Sandbox running and automatically launching Lockdown Browser.

**Comment by bluesangheili** [comment]
Never mind, I managed to fix this issue. Knowing absolutely nothing and solving it is truly the masterful way of the programmer.

**Comment by ryangodburn** [comment]
I think this happens when lockdown browser updates itself inside the sandbox. To try to fix, just redownload the lockdown browser install exe and swap it out from the old one in the runtime directory.

**Comment by bluesangheili** [comment]
Thanks, I managed to get it fixed.
