### ISSUE TITLE
I cannot get past running the build.ps1

### ISSUE THREAD

**Issue by codimac14** [gucci-on-fleek/lockdown-browser#40]
![17002723140652611638673675021092](https://github.com/gucci-on-fleek/lockdown-browser/assets/74572144/ff64a431-7756-43e8-960e-22d5487ddfba)

**Comment by codimac14** [comment]
So I didn't download the correct Visual Studio extensions. I fixed that, but now after I run Sandbox.wsb nothing happens. I waited like 10 minutes.

**Comment by codimac14** [comment]
I got it to work. I had to open sandbox as admin, try to launch the Sandbox.wsb, after which it told me that I cannot have 2 sandbox programs running at the same time. I closed the sandbox window, and then I reran the Sandbox.wsb by clicking it in the file. It is now working. for some reason it would not run it until I opened the sandbox for the first time after running the build.ps1.

Also, a side note, Norton 360 anti-virus flags and deletes the GetSystemMetrics file. It recognizes it as a Heuristic Virus and removes it. I had to override that file to prevent it from being deleted. This is a common issue for coders who have Norton 360.

**Comment by emicovi** [comment]
thank you for the upadte. Do you think it will work with the current lockdown browser version and also future ones?

**Comment by bluesangheili** [comment]
> thank you for the upadte. Do you think it will work with the current lockdown browser version and also future ones?

LockDown Browser updates look very sketchy to me, their updates are "security improvements" piled on one another. I am skeptical they are continuously pushing meaningful updates forward to avoid cheaters. As any company, they place money above all else. What is another broken down PC, after all?

**Comment by codimac14** [comment]
> thank you for the upadte. Do you think it will work with the current lockdown browser version and also future ones?

As of this time it works with the current updates. I cannot say for sure if it will work on future updates because I did not write the code. I would ask the repository owner.

**Comment by gucci-on-fleek** [comment]
@codimac14
> It is now working. for some reason it would not run it until I opened the sandbox for the first time after running the build.ps1

Not sure why that's happening, but at least it works now.

> Also, a side note, Norton 360 anti-virus flags and deletes the GetSystemMetrics file. It recognizes it as a Heuristic Virus and removes it. I had to override that file to prevent it from being deleted. This is a common issue for coders who have Norton 360.

I'm not sure why Norton would remove that file. I mean, it's a C++ file, it can't do anything at all unless you compile it. But if you have a C++ compiler installed and know how to use it, then you probably know enough to make sure that it's not malware. 

But that being said, the file does hook into some Windows functions, which is something that malware tends to do much more often than regular programs. Not much I can do here unfortunately.

@emicovi
> thank you for the upadte. Do you think it will work with the current lockdown browser version and also future ones?

Probably, but they could change anything in a future update, so you can never really be sure. And considering #52, an update seems especially likely.
