### ISSUE TITLE
Problems exiting the exam screen

### ISSUE THREAD

**Issue by wabwest10** [gucci-on-fleek/lockdown-browser#47]
I recently had a problem with the Sandbox on Respondus, as everything went smoothly and therefore the Sandbox started correctly and Respondus worked correctly even during the exam. However, when the exam time expired… no I was no longer able to exit the exam screen where "0 seconds remaining" was shown as the duration of the exam was over, so to be able to exit the exam despite having to exit automatically when the time available for the exam was over I I clicked on submit to send the exam and when I did I exited the exam screen, but a red bar with the word "error" was shown at the top and then I decided to close Blackboard. what caused this anomaly regarding the fact that at the end of the time available for the exam I did not automatically exit the exam screen and therefore I had to click on submit to exit and when I did I found a bar with error written . how can it be solved? Is it nothing serious or is it a bug? Is the exam still sent correctly? I kindly await an urgent response to this problem. many thanks in advance

**Comment by goldieee3** [comment]
Was your exam submitted? What does your school's portal say?

**Comment by wabwest10** [comment]
I can't know this as I withdrew from the exam, but as I wrote above in the exam portal when I clicked submit it gave me a small red bar with the word "error".

**Comment by wabwest10** [comment]
> Was your exam submitted? What does your school's portal say?

so what do you think could be due to this problem when you have to click submit on the exam? because it gives me a red bar with an error written on it and because I have to click on submit to exit the exam, as normally it should automatically exit the exam screen when the available time is over and therefore usually there is no need to click on submit

**Comment by gucci-on-fleek** [comment]
@wabwest10

> when the exam time expired… no I was no longer able to exit the exam screen where "0 seconds remaining" was shown as the duration of the exam was over, so to be able to exit the exam despite having to exit automatically when the time available for the exam was over I I clicked on submit to send the exam and when I did I exited the exam screen, but a red bar with the word "error" was shown at the top and then I decided to close Blackboard. what caused this anomaly regarding the fact that at the end of the time available for the exam I did not automatically exit the exam screen and therefore I had to click on submit to exit and when I did I found a bar with error written . how can it be solved? Is it nothing serious or is it a bug?

This looks like a bug to me, but a bug with the _Lockdown Browser_ itself, not this tool. As far as I'm aware, the modifications that this tool makes only affect the _Browser_'s startup process, so anything that happens after that is likely something else.

> Is the exam still sent correctly?

Hopefully, but if it wasn't, there's unfortunately nothing that can be done now, after the fact. You're _probably_ fine though—usually these systems upload your work continuously to the school's servers so that if your internet were to completely drop in the last five minutes of the exam, all your work up to that point would be automatically saved and submitted.
