### ISSUE TITLE
Error with date or firewall

### ISSUE THREAD

**Issue by potasio1** [gucci-on-fleek/lockdown-browser#49]
Hello, 
i have two issues: 

1. When I run the sandbox, it doesn't automatically run the lockdown browser.
2. When I run sandbox , then go in to the folder and open manually lockdown it shows this error.

Please help!!

Thank you so much in advance,

<img width="453" alt="Captura de pantalla 2024-01-25 a las 12 13 43" src="https://github.com/gucci-on-fleek/lockdown-browser/assets/157383845/69afa656-4645-4550-a97f-e24c3901a706">.

**Comment by MasterKingSirPlease** [comment]
I'm getting the same error, how did you solve it?

**Comment by potasio1** [comment]
> I'm getting the same error, how did you solve it?

still not solved

**Comment by gucci-on-fleek** [comment]
That's really weird. Is your date and time correct? If it is, try opening each of these links in a regular browser outside of the _Sandbox_:

```text
https://server-profiles-respondus-com.s3-external-1.amazonaws.com
https://static-public-downloads-cloud.respondus.com
https://www.respondus.com
https://help-center-respondus-com.s3.amazonaws.com
https://smc-service-cloud.respondus2.com
```

It's fine if you get an “Access Denied” message, but if you get a “page not found” or “connection failure” message for **any** of those 5 links, then that suggests that you have a firewall issue of some sort. How you would fix that would depend on where the firewall is, but regardless, it wouldn't be a bug/issue with this project.

If all of those links work and your clock is correct, then I'm not sure what the issue is. Maybe try adding

```xml
<Networking>Enable</Networking>
```

to `Sandbox.wsb`, between `<configuration>`/`</configuration>`:

https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/src/Sandbox.wsb#L6-L19

_([source](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-configure-using-wsb-file#networking))_

Make sure to fully-rebuild the files after changing that.

**Comment by randon358** [comment]
how can i modify the clock? i am facing the same error and have added the networking into sandbox.wsb.

currently the clock on my default system is DD/MM/YYYY, but in sandbox it is MM/DD/YYYY

**Comment by randon358** [comment]
it seems like if setting the time automatically would solve it, is there a workaround for this?
![photo_2024-02-26_12-08-36](https://github.com/gucci-on-fleek/lockdown-browser/assets/77784600/41b7aeb8-5075-4b37-a9ff-667fdd265efe)

**Comment by gucci-on-fleek** [comment]
@randon358 

> how can i modify the clock? i am facing the same error and have added the networking into sandbox.wsb.

Outside the _Sandbox_ (on the host computer), I think that it's something like “Settings  <kbd>&gt;</kbd> Time and Language <kbd>&gt;</kbd> Set Time and Date”. But the time is almost certainly correct on your host computer, and it'll sync automatically into the _Sandbox_, so I really doubt that that's the issue. 

> currently the clock on my default system is DD/MM/YYYY, but in sandbox it is MM/DD/YYYY 

Nope, that's for sure not the issue. The only reason that you need the correct time is for TLS/PKI stuff, but that's all done in UTC, so your locale setting doesn't matter at all. 

> it seems like if setting the time automatically would solve it, is there a workaround for this?
> ![photo_2024-02-26_12-08-36](https://github.com/gucci-on-fleek/lockdown-browser/assets/77784600/41b7aeb8-5075-4b37-a9ff-667fdd265efe)

Are the date, time, and time zone all correct inside the _Sandbox_? If so, then it shouldn't really matter. 

I'd guess that you're having the same issue as #58; that is, there's some weird firewall issue going on.

**Comment by RalfAkar** [comment]
I am also having the same problem. I ran the lockdown browser from the runtime_directory in the Windows sandbox and also tried to open the PowerShell and put this command: cd C:\Users\WDAGUtilityAccount\Desktop\runtime_directory\
.\withdll.exe /d:GetSystemMetrics-Hook.dll "C:\Program Files (x86)\Respondus\LockDown Browser\LockDownBrowser.exe"

I got this response: withdll.exe: DetourCreateProcessWithDllEx failed: 2

Maybe this helps to solve this problem.

**Comment by RalfAkar** [comment]
If there is a way to fix this could you please explain since you have closed the issue?

**Comment by gucci-on-fleek** [comment]
@RalfAkar 

> If there is a way to fix this could you please explain since you have closed the issue?

I'm not the one who closed this issue, but have you tried the instructions in https://github.com/gucci-on-fleek/lockdown-browser/issues/49#issuecomment-1937011554?



> That's really weird. Is your date and time correct? If it is, try opening each of these links in a regular browser outside of the _Sandbox_:
> 
> ```
> https://server-profiles-respondus-com.s3-external-1.amazonaws.com
> https://static-public-downloads-cloud.respondus.com
> https://www.respondus.com
> https://help-center-respondus-com.s3.amazonaws.com
> https://smc-service-cloud.respondus2.com
> ```
> 
> It's fine if you get an “Access Denied” message, but if you get a “page not found” or “connection failure” message for **any** of those 5 links, then that suggests that you have a firewall issue of some sort. How you would fix that would depend on where the firewall is, but regardless, it wouldn't be a bug/issue with this project.
> 
> If all of those links work and your clock is correct, then I'm not sure what the issue is. Maybe try adding
> 
> ```
> <Networking>Enable</Networking>
> ```
> 
> to `Sandbox.wsb`, between `<configuration>`/`</configuration>`:
> 
> https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/src/Sandbox.wsb#L6-L19
> 
> _([source](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-configure-using-wsb-file#networking))_
> 
> Make sure to fully-rebuild the files after changing that.

That solved the issue for some other people (see https://github.com/gucci-on-fleek/lockdown-browser/issues/58#issuecomment-1951412482), so it's worth trying.

**Comment by randon358** [comment]
the 5 links work with no issue and the clock is correct

i have added the networking into the files and the problem still occurs. perhaps it could be due to the VPN that the school requires using to access respondus

**Comment by gucci-on-fleek** [comment]
@randon358

> i have added the networking into the files and the problem still occurs. perhaps it could be due to the VPN that the school requires using to access respondus

Ahh, yep, that's probably it. I'm not really sure how to fix it, but here are some ideas:

1. Install the VPN inside the _Sandbox_. You'll need to reinstall it every time that you launch the _Sandbox_, so it'll be a bit annoying. And this may not even be possible—the VPN might need some low-level networking abilities that don't work inside the _Sandbox_. But if this does work, it's probably the easiest option.

2. You can try bridging the network adapters. [Here's a guide that looks mostly correct](https://www.thewindowsclub.com/create-a-network-bridge-windows). You'll want to bridge the _Sandbox_'s network adapter (probably named “Hyper-V” or something similar) to your VPN's adapter (which could be named just about anything). You'll probably have to fiddle around quite a bit with this option, but it _should_ work eventually.

**Comment by randon358** [comment]
1. installed VPN inside the sandbox - vpn successfully downloaded and connected but same error still appears
2. no networks are being detected inside the sandbox, even after connecting to the VPN there are still no networks

**Comment by gucci-on-fleek** [comment]
@randon358 

> 1. installed VPN inside the sandbox - vpn successfully downloaded and connected but same error still appears

Hmm, well that's disappointing.
 
> 2. no networks are being detected inside the sandbox, even after connecting to the VPN there are still no networks

You need to bridge the network outside of the _Sandbox_, on your host computer. That way you're bridging the VPN into the _Sandbox_.

**Comment by randon358** [comment]
these are the steps i did:
1. created new virtual switch for hyperv through hyperv manager
2. connected virtual switch to external network 
3. attempted to bridge vpn (pulse secure) with hyperv but stuck on loading page 

not sure if this will work on school network

**Comment by RalfAkar** [comment]
From what I have read so far, it seems a bit hard to do this on my computer. Our computers are given by the school and come with an antivirus that can not be disabled. This might be interfering with the files. I am going to try these on another computer and will update if it works on the other computer.
