### ISSUE TITLE
" This browser can't be used while Remote Desktop or Terminal Services are active."

### ISSUE THREAD

**Issue by Breakz1** [gucci-on-fleek/lockdown-browser#5]
This error comes up when you must open "Lockdown Browser" from within a school webpage (in this case,  a D2L quiz page). The browser (e.g Edge) will launch LockDown Browser and the error comes up.

Manually launching doesn't work since some schools make it so that the Respondus browser can't navigate to any website. All that is shown when the browser is launched by starting the VM or manually starting is the [following message as shown in this link.](https://support.respondus.com/hc/en-us/articles/4409607299355-LockDown-Browser-should-not-be-used-to-log-in-to-your-Learning-System)

**Comment by Breakz1** [comment]
Here's a temporary link of the browser (and its version) : https://trilinder.pythonanywhere.com/gGyG
I can send my credentials to log in the school website via email or discord DM if necessary.

**Comment by gucci-on-fleek** [comment]
This is hopefully fixed with the latest commit. Please let me know whether or not that solves the issue.

**Comment by Breakz1** [comment]
It fixed the issue. Thank you very much!
