### ISSUE TITLE
ALEKS doesn't play well?

### ISSUE THREAD

**Issue by HazEaSSaSSin** [gucci-on-fleek/lockdown-browser#51]
Haven't really had too many issues prior to now. It seems a PreCalc class uses a site called ALEKS to administer its tests and such. ALEKS redirects to download a version of Lockdown called "LockDownBrowserOEMSetup.exe", and after installation, it doesn't even put an icon on the desktop of the WSB. 

When I attempt to open it, it just simply says "Settings Restored" and instructs to open from a browser. ALEKS will only detect this OEM version as installed, so I can't use a different lockdown version, and when I attempt to launch directly through that site, it detects the VM settings. Any idea how to get around this, or you think we're just kinda SOL on the OEM version of LDB? 

![lockdown](https://github.com/gucci-on-fleek/lockdown-browser/assets/136451112/c2d5655a-f0bd-4de3-b3f7-06eda00c65c4)

**Comment by gucci-on-fleek** [comment]
Ok, so the good news here is that the installer worked (mostly) as expected. That's good since lots of the other people with the OEM version have had bad luck getting the installer to work.

> when I attempt to launch directly through that site, it detects the VM settings.

The regular _Lockdown Browser_ uses an `rldb://` URL protocol to open from a link. So either the installer isn't properly modifying the `rldb` protocol, or this version uses a different protocol. Try running 

https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/runtime_directory/sandbox_run.ps1#L39

inside the _Sandbox_ and see if that fixes anything. If not, you'll need to figure out what the correct protocol to use is. To do that, either copy the “launch in Lockdown Browser” link and see what protocol it uses, or search through the registry at `HKCR` (`HKEY_CLASSES_ROOT`) for the full path to wherever the _Browser_ executable was installed. Then, you can modify the above line with the correct protocol.

**Comment by HazEaSSaSSin** [comment]
Appreciate that! I'll give it a shot tonight and post an update here if it works successfully. Good looks

**Comment by HazEaSSaSSin** [comment]
I may be slightly out of my element, but it looks to just use an https:// protocol. 
![ldb-link-1](https://github.com/gucci-on-fleek/lockdown-browser/assets/136451112/c862597a-f0cd-46df-89d9-b48994d58f81)

I also looked through the registry, but it seems as though the LDB registered a number of different URL protocols. 
![reg-entry-1](https://github.com/gucci-on-fleek/lockdown-browser/assets/136451112/23d42069-382b-455d-a65c-7ee45858ae70)
![reg-entry-2](https://github.com/gucci-on-fleek/lockdown-browser/assets/136451112/19292068-1f88-4861-81cc-5b044a9679cb)
![reg-entry-3](https://github.com/gucci-on-fleek/lockdown-browser/assets/136451112/70a9b22a-b166-401e-82f7-d1f54675a8b6)
![reg-entry-4](https://github.com/gucci-on-fleek/lockdown-browser/assets/136451112/7c8ad60c-c9fc-4f9e-8b50-ba3cda2b8f88)
![reg-entry-5](https://github.com/gucci-on-fleek/lockdown-browser/assets/136451112/004ae018-6de0-479b-afb7-973a2db3495a)

All of these entries point to the same .exe and are identical. Is it possible to modify the above PS file to account for all of these?

**Comment by gucci-on-fleek** [comment]
@HazEaSSaSSin

> I may be slightly out of my element, but it looks to just use an https:// protocol. ![ldb-link-1](https://private-user-images.githubusercontent.com/136451112/303921359-c862597a-f0cd-46df-89d9-b48994d58f81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTQwMzIsIm5iZiI6MTcwNzcxMzczMiwicGF0aCI6Ii8xMzY0NTExMTIvMzAzOTIxMzU5LWM4NjI1OTdhLWYwY2QtNDZkZi04OWQ5LWI0ODk5NGQ1OGY4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmI1NGZiYTJhZmY1OGFiMTdjZjVmMTQwZGVhMGJjMzkxZmNmMzM1MTgzNDZjNjE2NGQzMjJjZGVmMDI1MjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Z7_VDJJrq53MOTKwGlowjsdZZOp2AJC4q2hNGzNQM8)

Yeah, that URL is just `https://`, so it must at some point redirect to a `rldb://` or `ldb://` protocol.

> I also looked through the registry, but it seems as though the LDB registered a number of different URL protocols. ![reg-entry-1](https://private-user-images.githubusercontent.com/136451112/303922226-23d42069-382b-455d-a65c-7ee45858ae70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTQwMzIsIm5iZiI6MTcwNzcxMzczMiwicGF0aCI6Ii8xMzY0NTExMTIvMzAzOTIyMjI2LTIzZDQyMDY5LTM4MmItNDU1ZC1hNjVjLTdlZTQ1ODU4YWU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGYyOTU2NDYxYzU5ZDI2ZmZhNmMyMmE3ODljOTllYTVjZmRjNmE5ODY4ODBkZjVkYWI0NzExMDBhMDE2MDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8fcmUfRBmtF0pYnpcVox5Erjtc2sZH8Vvx0AQXok6kQ) ![reg-entry-2](https://private-user-images.githubusercontent.com/136451112/303922229-19292068-1f88-4861-81cc-5b044a9679cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTQwMzIsIm5iZiI6MTcwNzcxMzczMiwicGF0aCI6Ii8xMzY0NTExMTIvMzAzOTIyMjI5LTE5MjkyMDY4LTFmODgtNDg2MS04MWNjLTViMDQ0YTk2NzljYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmJjM2FhMmFlMTQ1MWJhYjc3N2ZmYTg4YTgxMzg3NGI5MjQ1MjAyOTExY2Q1Njc3ZmM3MjE1ZjQ2MDgzZjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x80EKdQI1VusNvwUojgALs71_PfQdaXsRfV4YcW9eCc) ![reg-entry-3](https://private-user-images.githubusercontent.com/136451112/303922230-70a9b22a-b166-401e-82f7-d1f54675a8b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTQwMzIsIm5iZiI6MTcwNzcxMzczMiwicGF0aCI6Ii8xMzY0NTExMTIvMzAzOTIyMjMwLTcwYTliMjJhLWIxNjYtNDAxZS04MmY3LWQxZjU0Njc1YThiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTMzY2Q4NWFiZTdlMzIzODQ1NDMwMjgxMzM2ZWE2ZjY5OTc2OWRkOWQzMjAxMDIzZmU4MzljY2EwMzBmYTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TTHkx4_E4Z2VL_ESMG7713cRXEycS3hq7HqHI4Zo85c) ![reg-entry-4](https://private-user-images.githubusercontent.com/136451112/303922231-7c8ad60c-c9fc-4f9e-8b50-ba3cda2b8f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTQwMzIsIm5iZiI6MTcwNzcxMzczMiwicGF0aCI6Ii8xMzY0NTExMTIvMzAzOTIyMjMxLTdjOGFkNjBjLWM5ZmMtNGY5ZS04YjUwLWJhM2NkYTJiOGY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDI1YjgxNzQ3ZGUzZDMwODc2NjQ3ODE5ZjlmMDhjOWYyZTU5ZTM5YTk2ZjZmZTE3ZjZlODE0NWExMTU5NGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h6xwUmBeORyy8XIu8YR6y_MBCVtIeGADfuI-pvcc2D0) ![reg-entry-5](https://private-user-images.githubusercontent.com/136451112/303922233-004ae018-6de0-479b-afb7-973a2db3495a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTQwMzIsIm5iZiI6MTcwNzcxMzczMiwicGF0aCI6Ii8xMzY0NTExMTIvMzAzOTIyMjMzLTAwNGFlMDE4LTZkZTAtNDc5Yi1hZmI3LTk3M2EyZGIzNDk1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGY0YzA4OTgwY2RmMmM1ODU3NTFlMmExNTNkYzRlY2MwOWM2YTRiNjNiNzFkZGMxMGU0OTM0MTliOTk5OWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BoqG3WSGBlD4YybbgCquc0xIQRzbm8GRA0x7NahK9Is)
> 
> All of these entries point to the same .exe and are identical. Is it possible to modify the above PS file to account for all of these?

Sure, try replacing `sandbox_run.ps1` with this (completely untested):

```powershell
# Lockdown Browser in Windows Sandbox
# https://github.com/gucci-on-fleek/lockdown-browser
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2020-2024 gucci-on-fleek

# DON'T RUN THIS ON YOUR REGULAR SYSTEM! IT WILL CAUSE **IRREVERSIBLE** DAMAGE

$ErrorActionPreference = "Stop"
Set-StrictMode -Version 3

cd $PSScriptRoot

$lockdown_extract_dir = "C:\Windows\Temp\Lockdown"
$lockdown_runtime = "C:\Program Files (x86)\Respondus\LockDown Browser\LockDownBrowser.exe"
$lockdown_installer = (ls Lockdown*)[0]

Get-ChildItem -Path "HKLM:\HARDWARE\DESCRIPTION" | Remove-ItemProperty -Name SystemBiosVersion -ErrorAction Ignore
rm HKLM:\HARDWARE\DESCRIPTION\System\BIOS -ErrorAction Ignore

# We're in a short-lived VM, so we can safely delete any necessary files
$vmcompute_path = "C:\Windows\System32\VmComputeAgent.exe"
takeown /f $vmcompute_path
icacls $vmcompute_path /grant "Everyone:(D)"
rm $vmcompute_path

& $lockdown_installer /x "`"$lockdown_extract_dir`"" # Dumb installer needs a quoted path, even with no spaces. Also, we have to extract the program before we can even run a silent install.
while (!(Test-Path $lockdown_extract_dir\id.txt)) {
    # This is the easiest way to detect if the installer is finished extracting
    sleep 0.2
}
sleep 1
kill -Name *Lockdown*

& "$lockdown_extract_dir\setup.exe" /s "/f1$PSScriptRoot\setup.iss" "/f2$PSScriptRoot\..\setup.log" # If we don't give a log file path, this doesn't work
Wait-Process -Name "setup"

# Support use of the `rldb://` URL protocol
New-PSDrive -PSProvider registry -Root HKEY_CLASSES_ROOT -Name HKCR
Set-ItemProperty -ErrorAction Ignore -Path "HKCR:\rldb\shell\open\command" -Name "(Default)" -Value ('"' + $PSScriptRoot + '\withdll.exe" "/d:' + $PSScriptRoot + '\GetSystemMetrics-Hook.dll" ' + $lockdown_runtime + ' "%1"')
Set-ItemProperty -ErrorAction Ignore -Path "HKCR:\anst\shell\open\command" -Name "(Default)" -Value ('"' + $PSScriptRoot + '\withdll.exe" "/d:' + $PSScriptRoot + '\GetSystemMetrics-Hook.dll" ' + $lockdown_runtime + ' "%1"')
Set-ItemProperty -ErrorAction Ignore -Path "HKCR:\cllb\shell\open\command" -Name "(Default)" -Value ('"' + $PSScriptRoot + '\withdll.exe" "/d:' + $PSScriptRoot + '\GetSystemMetrics-Hook.dll" ' + $lockdown_runtime + ' "%1"')
Set-ItemProperty -ErrorAction Ignore -Path "HKCR:\ielb\shell\open\command" -Name "(Default)" -Value ('"' + $PSScriptRoot + '\withdll.exe" "/d:' + $PSScriptRoot + '\GetSystemMetrics-Hook.dll" ' + $lockdown_runtime + ' "%1"')
Set-ItemProperty -ErrorAction Ignore -Path "HKCR:\ldb\shell\open\command" -Name "(Default)" -Value ('"' + $PSScriptRoot + '\withdll.exe" "/d:' + $PSScriptRoot + '\GetSystemMetrics-Hook.dll" ' + $lockdown_runtime + ' "%1"')
Set-ItemProperty -ErrorAction Ignore -Path "HKCR:\ldb1\shell\open\command" -Name "(Default)" -Value ('"' + $PSScriptRoot + '\withdll.exe" "/d:' + $PSScriptRoot + '\GetSystemMetrics-Hook.dll" ' + $lockdown_runtime + ' "%1"')

./withdll /d:GetSystemMetrics-Hook.dll $lockdown_runtime
```

If that works, then I'll add those lines into the main file.

**Comment by HazEaSSaSSin** [comment]
Sorry about that delay, @gucci-on-fleek . You can mark this as closed now. I actually ended up dropping that class cuz I'm too busy lol. I wasn't able to confirm whether or not it worked because I can no longer access the course. Appreciate you checkin, though.
