### ISSUE TITLE
"LockDown Browser has been illicitly modified" message in v2.0.9.00

### ISSUE THREAD

**Issue by gucci-on-fleek** [gucci-on-fleek/lockdown-browser#6]
After updating the _Lockdown Browser_ to version 2.0.9.00, the browser refuses to load and presents the following warning in a message box:

> LockDown Browser has been illicitly modified, or your PC is unable to validate its certificate. The software will now shut down and you will be unable to continue. We recommend performing a Windows update to see if that fixes the issue. Your instructor has been notified of this issue.

This is a known issue, **with no current fix available**. I am currently working on patching this; however, it may be some time until a fix is available. Any PRs to fix the issue will be greatly appreciated.

**Comment by mayed505** [comment]
Hey @gucci-on-fleek,

I've stumped upon this post which refers to the same message error:
https://systemfailu.re/2020/11/14/lockdownbrowser-analysis/

Go down to "<:: MISC. DETECTIONS" and you will find how this is being done.

The following message on that article is:
"_The best assumption I could make about this function is that it ensure the name of the exe currently running is ‘LockDownBrowser.exe” and has not changed or been modified. If this returns false, meaning the module name is not the same, then it will send the modified message to the main loop._"

Maybe looking into it we could probably know how they are checking the integrity.

**Comment by gucci-on-fleek** [comment]
I can't tell exactly how they're detecting this, but my guess is that they're just detecting if _Detours_ has been loaded or not. However they are doing it, they just started detecting this in this last update.

Probably the "easiest" solution would be to patch the system file `user32.dll` to make `GetSystemMetrics(SM_REMOTESESSION)` always return false. The patch itself should only need like 10 lines of assembly, but correctly applying the patch on a running system may be a little tricky.

**Comment by mayed505** [comment]
Wouldn’t it be possible to patch the DLL in memory theoretically?

Also regarding the GetSystemMetrics, they could possibly also be looking into [GetVersionEx](http://msdn.microsoft.com/en-us/library/ms724451%28v=vs.85%29.aspx) ([OSVERSIONINFOEX.wSuiteMask](http://msdn.microsoft.com/en-us/library/ms724833%28v=vs.85%29.aspx)) but I’m not sure as I could be wrong.

I’d need to fiddle around on that part, I’ll try getting around and see if I can do a real-time patch on that one with a DLL injector that I have laying around. Possibly even go the hard way of modifying LockdownBrowser.dll with a byte patch.

**Comment by mayed505** [comment]
Any update on the user32.dll's patch?

**Comment by gucci-on-fleek** [comment]
@mayed505 It's somewhere on "the list", although not particularly high up. Realistically, I'm unlikely to start working on this until September, although I may end up with some spare time in the next couple of weeks. No solid plans at the moment, although it will probably get done eventually.

**Comment by mayed505** [comment]
@gucci-on-fleek I've attempted to play with the user.dll and all but it doesn't seem to work up correctly.

The best bet is to leave it up to you because I'm probably doing something wrong here.

**Comment by gucci-on-fleek** [comment]
@mayed505 

Which `user32.dll` were you modifying? You would need to patch the one in `C:\Windows\SysWOW64`, **not** the one in `C:\Windows\System32`.

**Comment by mayed505** [comment]
@gucci-on-fleek 

I have no idea what I've done, but I updated the lockdown, and it seems to be working.
https://i.imgur.com/NzZjFQL.png

It used to show that dialog upon the browser start-up.

Checking the change log since July 26 reveals the following:

```Version 2.0.9.03, 7-26-22
Improvements to security```

**Comment by mayed505** [comment]
This probably should be closed. Issue hasn’t occurred since the issue was made.
