### ISSUE TITLE
Detour Alternative

### ISSUE THREAD

**Issue by krulci** [gucci-on-fleek/lockdown-browser#7]
As Detour do not seem to support Windows SDK 10.0.22000.0 and 10.0.22621.0 yet, are there other alternative for injection? On my Windows 11 system I kept getting the missing .dll error whereas everything is smooth in a clean install of Windows 10 environment.

**Comment by gucci-on-fleek** [comment]
I don't have easy access to a Windows 11 system right now, but I'd be surprised if Detours didn't work there. My best guess is that the version of Detours that I've pinned is too old for Windows 11. 

Try running:
```sh
git submodule update --remote
```
and then rerun the build script.

If that works, let me know and I'll apply that update to this repo. If it doesn't work, please reply with the output of the build script and I'll try and figure something out.

**Comment by krulci** [comment]
I had tried with the newest detour as well.
I was partially able to build Detour with Visual Studio but do get some error in the end.
The problem I faced was about missing dlls in C:\Program Files (x86)\Windows Kit folder.
But, indeed Windows 10 works flawless.

**Comment by gucci-on-fleek** [comment]
Hmm, that's odd. I'll try and get a Windows 11 VM up sometime next week to do some further testing.

**Comment by krulci** [comment]
So I just installed these three SDKs sequentially:
10.0.19041.0
10.0.22000.194
10.0.22621.755
Either installing from sdk-archive make a difference from installing from Visual Studio Installer
Or I really forgot to update the submodule.
All three version built.
However, none was able to launch the browser in sandbox as in Windows 10
