### ISSUE TITLE
LockDown Browser May Be Banning Your Institutional Account

### ISSUE THREAD

**Issue by bluesangheili** [gucci-on-fleek/lockdown-browser#71]
I tried to mess around with ldb from two entirely different computers, one warning in the first one, second warning to my other computer. The only way I can make sense out of this is they are targeting your login credentials. OEM ldbs are not affected by this.

**Comment by gucci-on-fleek** [comment]
Ah, that's unfortunate. I'm going to close this issue as a duplicate of #65; but please, feel free to continue the discussion there. And thanks for the report.
