### ISSUE TITLE
Running build.ps1 no longer works with the current version of Visual Studio C++ Tools.

### ISSUE THREAD

**Issue by ThunderRuler** [gucci-on-fleek/lockdown-browser#9]
```
nmake : The term 'nmake' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.
```
It seems to me that this is an issue with Microsoft more than it is with this repo but an updated guide would nice. Unless there's a quick fix that I haven't been able to find yet.

**Comment by gucci-on-fleek** [comment]
Did you install the [Visual Studio C++ Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) first? That error message suggests that the compiler isn't correctly installed. 

If you think that you've correctly installed the compiler, then try running the script from a Visual Studio Developer Tools command prompt. There should be something with a similar name as that in your Start Menu somewhere. Pick the `x86` one.

Otherwise, does the script have any other output before that error message?

**Comment by gucci-on-fleek** [comment]
I'm closing this issue since I haven't received any further updates and I suspect that the [Visual Studio C++ Tools](https://github.com/gucci-on-fleek/lockdown-browser#system-requirements) weren't properly installed.

If you are still having issues, please feel free to reopen this issue.

**Comment by Spimy** [comment]
Not able to build for the same reasons:
```PS
PS E:\Downloads\lockdown-browser> .\build.ps1

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files (x86)\PackageManagement\ProviderAssemblies' or
'C:\Users\William\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install
and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
The system cannot find the path specified.
nmake : The term 'nmake' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At E:\Downloads\lockdown-browser\build.ps1:40 char:5
+     nmake
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (nmake:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```
![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/34989646/00188f30-0daa-4528-9bf6-04c056b9b660)
![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/34989646/168507e5-ec73-49b8-8ab2-23a6981f2a39)

**Comment by Spimy** [comment]
Nevermind, reinstalled and everything good

**Comment by ThunderRuler** [comment]
Sorry to revive this thread, it looks like I never responded back. I had incorrectly installed the prerequisites and reinstalling them solved the issue. Also it looks like this works on Windows 11 without issue.
